@startuml

class User{
    String name
    String email
    String password
    boolean confirmed
    Date createdAt
    Date birthDate 
  }

class Role {
    
  }

class Permission{
    string name 
    string description 
  }

class UserSettings{
    int calibration 
    Intensity intensity
    boolean notify
    boolean notifyVibrate
    int vibrateIntensity
  }
class Training{
    period period 
    intensity intensity
  }
class Readout{
    int cervival
    int dorsal
    date timestamp
  }

User "1" *-- "1" UserSettings
User "1" -- "*"  Training 
User "1" -- "*" Readout
Training "1" *-- "*" Readout
Role "1" *-- "*" Permission 
User "*" *-- "*" Role 

@enduml

