@startuml
left to right direction 

User "1" *-- "1" UserSettings
User "1" -- "*"  Training 
Role "1" *-- "*" Permission 
User "*" *-- "*" Role 
class User{
    String name
    String email
    String password
    boolean confirmed
    Date createdAt
    Date birthDate 
  }

class Role {
    String name
    String description
  }

class Permission{
    string name 
    string description 
  }

class UserSettings{
    int calibration 
    Intensity intensity
    boolean notify
    boolean notifyVibrate
    int vibrateIntensity
  }
class Training{
    period period 
    intensity intensity
  }
class Intensity{
    LOW
    MEDIUM
    HIGHT
  }
@enduml

