@startuml Authentication_sequence
!pragma teoz true
box "Front-end" #LightBlue
    participant Client as client
end box 
box "Back-end" #LightGreen
    box "Authentication_Server"
        boundary AuthApi  as auth_api 
    end box 

end box

database Database as DB
activate client
client -> auth_api: solicita token de acesso
activate auth_api
auth_api -> DB : consulta usuario 
activate DB
return  retorno da consulta 
    auth_api --> client: [user == null] notFound
    [<- client :
    auth_api --> client: [auth = false ] error
    [<- client :
    auth_api --> client: token de acesso 
    deactivate auth_api
    [<- client :
    
@enduml
